### ISSUE TITLE
Home - Unable to log in

### ISSUE THREAD

**Issue by junpaolo** [junpaolo/ePrice-validation-testing#1]
Scenario:
User will try to log in 

Observed Result:
Unable to log in. Error message displays

Expected Result:
Log in successful

![111](https://cloud.githubusercontent.com/assets/20081753/17758195/faa5d50e-651f-11e6-91d4-9bc990b7f107.png)

**Comment by jtolen** [comment]
Closed Issue

**Comment by junpaolo** [comment]
super comment 1
