### ISSUE TITLE
Price List and Groups - Manage Price List - Search Results Action button

### ISSUE THREAD

**Issue by jtolen** [junpaolo/ePrice-validation-testing#10]
Scenario:
Manage Price List: Active Search Price List Search result list

Observed Result: 
Unable to edit any result by clicking the action button

Expected Result:
User if admin, can edit any of the result just by clicking the action button

Test Steps:
1. Fill out all parameters with valid values
2. Click Search

![36](https://cloud.githubusercontent.com/assets/19830714/17795215/1b57e426-65e9-11e6-85ee-556387ba3f38.png)

**Comment by junpaolo** [comment]
Considered as OOS. See https://github.com/junpaolo/ePrice-validation-testing/issues/22
