### ISSUE TITLE
HOME -Page Layout 

### ISSUE THREAD

**Issue by coleenmarie** [junpaolo/ePrice-validation-testing#15]
**Scenario:** 
Incorrect label name,  label location and Manufacturer button

**Observed Result:** 
   a. "Search" label should be "Product Search" 
   b. "Indicates Required Field" label should be located inside the Filter By  
   c.  "Lens Type" should be "Selected Lens Type"
   d.  Defective UI button on "Manufacturer Expand"

**Expected Result:** 
Page Layout should be the same as defined from the Developer's notebook

![home page layout](https://cloud.githubusercontent.com/assets/20077923/17796177/5f8e23aa-65f1-11e6-97c7-87e0092f5e0c.png)

**Comment by vernonminer** [comment]
Updated Documentation. Screen labels are correct. Expand Manufacturer switch is not distorted in any browser I open the screen in.

**Comment by coleenmarie** [comment]
Setting the browser's zoom level to default size - Expand Manufacturer's switch is not distorted but other switches are distorted. Try changing the zoom level higher or lower to see other distorted switches as shown below. 

![image](https://cloud.githubusercontent.com/assets/20077923/17827270/825284ba-66ac-11e6-9c18-7f9f6f33c73c.png)

**Comment by vernonminer** [comment]
The bootstrap switch plug in allows for a limited switch width by default. It provides a method to increase the width, set  the width in pixels. This does not correct itself when the screen resolution changes, for instance in a high definition screen. The switch still performs as expected it just looks bad.
