### ISSUE TITLE
Price List and Groups - Manage Price Lists - Clear button (search)

### ISSUE THREAD

**Issue by jtolen** [junpaolo/ePrice-validation-testing#20]
Scenario:
Click Clear button with Inactive search input criteria and results

Observed Result: 
Input criteria was cleared but not the Previous search results

Expected Result:
Input criteria and previous search results will be cleared

Test Steps:
Click Clear button

![44](https://cloud.githubusercontent.com/assets/19830714/17796628/85f95962-65f4-11e6-9fe0-2c270879abf6.png)

**Comment by vernonminer** [comment]
Updated Stored Procs in PMReport DB and update DBContext in application

**Comment by junpaolo** [comment]
Still experiencing the same issue

![clear button search pricelist error](https://cloud.githubusercontent.com/assets/20081753/17990914/bd7d13e2-6b6c-11e6-9e09-f864bfca574d.png)

**Comment by vernonminer** [comment]
Updated JavaScript file

**Comment by junpaolo** [comment]
Still experiencing the same issue for both active and inactive
![search pricelist active error](https://cloud.githubusercontent.com/assets/20081753/18112658/d07a5ef8-6f5b-11e6-8e12-398f9fcfbb45.png)

![search pricelist inactive error](https://cloud.githubusercontent.com/assets/20081753/18112665/d87465ea-6f5b-11e6-93b7-46fead21f68b.png)

**Comment by vernonminer** [comment]
Please make sure to force the browser to download a new JavaScript file for this page.

**Comment by junpaolo** [comment]
fixed

![manage pricelist_search_clearbutton1](https://cloud.githubusercontent.com/assets/20081753/18188813/baceef1e-70e7-11e6-8aa4-70b6fbcb5725.png)

![manage pricelist_search_clearbutton2](https://cloud.githubusercontent.com/assets/20081753/18188821/cb1537c0-70e7-11e6-9c54-4f09ac9b5d4b.png)
