### ISSUE TITLE
Ranking Report - Badge count is set to 0 value

### ISSUE THREAD

**Issue by junpaolo** [junpaolo/ePrice-validation-testing#21]
Scenario:
User will validate the Ranking Report main page

Steps:
1. Click the Reports dropdown button from the navigation bar
2. Select Report List
3. Choose Ranking Report

Observed Result:
Product Group available items badge has a value of 0

Expected Result:
Each badge must reflect the total amount of items from the list

![ranking report main page error](https://cloud.githubusercontent.com/assets/20081753/17796721/7ab3b0b0-65f5-11e6-82ec-0cacea4044b2.png)

**Comment by vernonminer** [comment]
Corrected JavaScript file

**Comment by junpaolo** [comment]
fixed
![Uploading ranking report main page ok.png…]()
