### ISSUE TITLE
Price List and Groups - Manage Price List - Search Results Action button

### ISSUE THREAD

**Issue by jtolen** [junpaolo/ePrice-validation-testing#22]
Scenario:
Manage Price List: Inactive Search Price List Search result list

Observed Result: 
Unable to edit any result by clicking the action button

Expected Result:
User if admin, can edit any of the result just by clicking the action button

Test Steps:
1. Fill out all parameters with valid values
2. Click Search

![45](https://cloud.githubusercontent.com/assets/19830714/17796732/93368676-65f5-11e6-864a-c97ef4f1df7b.png)

**Comment by vernonminer** [comment]
Updated Stored Procs in PMReport DB and update DBContext in application

**Comment by junpaolo** [comment]
Still experiencing the same issue when searching with inactive status
![manage pricelist unable to edit](https://cloud.githubusercontent.com/assets/20081753/18112880/e8fd7d28-6f5d-11e6-83b0-6e1a799c4b98.png)

**Comment by vernonminer** [comment]
Because editing the details of a price list is not an available feature presently, I removed the action buttons from view.

**Comment by junpaolo** [comment]
considered as OOS
