### ISSUE TITLE
Price List and Groups - Manage Price List - Edit Search Results

### ISSUE THREAD

**Issue by jtolen** [junpaolo/ePrice-validation-testing#23]
Scenario:
Manage price List: Edit search result

Observed Result:
Action button has no action 

Expected Result:
Clicking Action button will enable to edit item from search results

Test Steps:
1. Search and select pricelist then click the edit button
2. Edit desired field/s
3. Click save/update button

![48](https://cloud.githubusercontent.com/assets/19830714/17796896/d813109c-65f6-11e6-914e-6bd24328217b.png)

**Comment by vernonminer** [comment]
Updated Stored Procs in PMReport DB and update DBContext in application

**Comment by junpaolo** [comment]
still experiencing the same issue when searching with active status
![manage pricelist unable to edit active](https://cloud.githubusercontent.com/assets/20081753/18112840/79c3f612-6f5d-11e6-946c-57e0386af8f9.png)

**Comment by vernonminer** [comment]
Updated JavaScript file

**Comment by junpaolo** [comment]
Action buttons N/A

![search and edit price lists_action button missing](https://cloud.githubusercontent.com/assets/20081753/18164002/4b426a3a-7070-11e6-9e84-0a34fb01af55.png)

**Comment by junpaolo** [comment]
considered as OOS. see https://github.com/junpaolo/ePrice-validation-testing/issues/22
