### ISSUE TITLE
Price List and Groups - Create Price List Groups

### ISSUE THREAD

**Issue by jtolen** [junpaolo/ePrice-validation-testing#24]
Scenario:
Creation of New Price List group

Observed Result:
Return error upon saving new price list group with completed mandatory fields. New Price List group was not saved.

Expected Result:
New price list group should be created with complete mandatory fields 

Test Steps:
1. Fill up the name and comment. Don’t include price lists
2. Click Save

![55](https://cloud.githubusercontent.com/assets/19830714/17797791/4c647c18-65fe-11e6-8d18-e630621974ce.png)

**Comment by vernonminer** [comment]
Updated Stored Procs in PMReport DB and update DBContext in application

**Comment by junpaolo** [comment]
fixed
![create pricelist group without pricelists](https://cloud.githubusercontent.com/assets/20081753/18112688/1bb3a6ea-6f5c-11e6-8b86-3c5f12c5328e.png)
