### ISSUE TITLE
Price List and Groups - Create Price List Groups

### ISSUE THREAD

**Issue by jtolen** [junpaolo/ePrice-validation-testing#25]
Scenario:
Creation of New Price List group

Observed Result:
Return error upon saving new price list group using all fields. New Price List group was not saved.

Expected Result:
New price list group should be created  

Test Steps:
1. Fill up the name and comment 
2. Select Price lists
3. Click Save

![56](https://cloud.githubusercontent.com/assets/19830714/17797818/7e1623ec-65fe-11e6-8262-7dc9abb339ef.png)

**Comment by vernonminer** [comment]
Updated Stored Procs in PMReport DB and update DBContext in application

**Comment by junpaolo** [comment]
fixed

![create pricelist group](https://cloud.githubusercontent.com/assets/20081753/18112214/83984d5a-6f58-11e6-81ff-5e5a7b8d6c0a.png)
