### ISSUE TITLE
PRODUCTS & GROUPS - Manage Products 

### ISSUE THREAD

**Issue by coleenmarie** [junpaolo/ePrice-validation-testing#26]
**Scenario:** 
Loading search in manage products
**Observed Result:**
While search is in progress  "undefined" text displays intermittently on top of  copy, excel, print button in search panel 
**Expected Result:**
there should be no "undefined" text displayed

![undefined intermittent](https://cloud.githubusercontent.com/assets/20077923/17798823/a2951c10-6607-11e6-9763-e99a2a6d5f9f.JPG)

**Comment by vernonminer** [comment]
There are too many products to return to allow the user to search without at least one criterion. I added code to the JavaScript file to display an error and corrected the display of the results that was causing the undefined display.

**Comment by junpaolo** [comment]
fixed
![Uploading no undefined in manage products.png…]()
