### ISSUE TITLE
Query - Set private query to inactive

### ISSUE THREAD

**Issue by jtolen** [junpaolo/ePrice-validation-testing#27]
Scenario:
Changing private query to inactive

Observed Result:
No action upon clicking the Save button. 

Expected Result:
private query should be set as Inactive, save changes.

Test Steps:
1. Click action button to edit query details
2. Select Active NO
3. Click Save button

![3](https://cloud.githubusercontent.com/assets/19830714/17800086/ad3cb528-6612-11e6-8e19-a31518d1fcdb.png)

**Comment by vernonminer** [comment]
See #29
