### ISSUE TITLE
Query - display of inactive public queries

### ISSUE THREAD

**Issue by jtolen** [junpaolo/ePrice-validation-testing#30]
Scenario:
Display of Inactive public queries

Observed Result:
No return result display for inactive public queries 

Expected Result:
Should display all inactive queries

Test Steps:
1. Click Public Queries
2. Set Active NO

![9](https://cloud.githubusercontent.com/assets/19830714/17800664/aeaf7dbe-6617-11e6-90da-a47876e85c0a.png)

**Comment by vernonminer** [comment]
List can be 0 entries when there are no inactive public queries. I updated the active status of a public query to be inactive. List display active or inactive as expected.

**Comment by jtolen** [comment]
Hi Vernon, Should I be able to see inactive public query even if I did not create it?
I updated 1 active public query and set it to inactive, but I did not create it and I cannot see it from the list display of inactive public queries.

**Comment by junpaolo** [comment]
Public queries are available for all users. User can update the query if the user has the privilege
