### ISSUE TITLE
Users - No Print/Export button is displayed in the New User page

### ISSUE THREAD

**Issue by jparala** [junpaolo/ePrice-validation-testing#32]
Scenario:
In Create New User page, click Print/Export button to print or export user details.

Observed Result:
No "Print / Export" button is displayed in the create new user page.

Expected Result:
"Print / Export" button is displayed in the page.

Screenshot:
![pic14](https://cloud.githubusercontent.com/assets/21092654/17802292/fabb8dd8-6621-11e6-93fd-d21eed3fb6b9.JPG)

**Comment by vernonminer** [comment]
Removed from documentation.

**Comment by junpaolo** [comment]
This will be considered as OOS
