### ISSUE TITLE
Users - Encountered Server Model Error when adding/saving the new user

### ISSUE THREAD

**Issue by jparala** [junpaolo/ePrice-validation-testing#33]
Scenario:
In create new user page, input details in all required fields and click "Save" button.

Observed Result:
A message "Server model error" is displayed.

Expected Result:
New user is successfully created.

Screenshot:
![pic13](https://cloud.githubusercontent.com/assets/21092654/17802352/5e7bd9c2-6622-11e6-8c6b-7b20db79d364.JPG)

**Comment by vernonminer** [comment]
Updated QA stored procedure to match DEV stored procedure.
