### ISSUE TITLE
Users - Encountered Error when updating existing user details

### ISSUE THREAD

**Issue by jparala** [junpaolo/ePrice-validation-testing#35]
Scenario:
In Edit User page, edit any details and click Save button.

Observed Result:
Encountered error when updating existing user details.

Expected Result:
Details are successfully updated.

Screenshot:
![pic27](https://cloud.githubusercontent.com/assets/21092654/17802523/5a4992d0-6623-11e6-8ec4-6dc7689594c0.JPG)

**Comment by vernonminer** [comment]
Updated QA stored procedure to match DEV stored procedure.

**Comment by junpaolo** [comment]
still experiencing the same error
]
![edit user failed](https://cloud.githubusercontent.com/assets/20081753/17928150/ebb633de-6a2b-11e6-90d8-18f521883811.png)

**Comment by vernonminer** [comment]
Retest was done prior to application update.

**Comment by junpaolo** [comment]
fixed

![edit user details1](https://cloud.githubusercontent.com/assets/20081753/17994435/4c5a9648-6b8b-11e6-9c37-0aae43190114.png)

![edit user details2](https://cloud.githubusercontent.com/assets/20081753/17994439/51b807e2-6b8b-11e6-8bf2-662058c6ec06.png)
