### ISSUE TITLE
Users - Encountered error when deleting existing user

### ISSUE THREAD

**Issue by jparala** [junpaolo/ePrice-validation-testing#36]
Scenario:
In Edit User page, click Delete button.

Observed Result:
An error "Failed to delete user, try again" is displayed.

Expected Result:
User is successfully deleted.

Screenshot:
![pic23](https://cloud.githubusercontent.com/assets/21092654/17802589/a6b20b48-6623-11e6-8c6c-51203869cf3e.JPG)

**Comment by vernonminer** [comment]
Updated stored procedures in QA DB to match DEV DB.

Note: Deleting user with active status = true will deactivate user. Deleting user with active status = false will remove user from DB.

**Comment by junpaolo** [comment]
Hi Vernon,

Can we delete a user with inactive status?

**Comment by junpaolo** [comment]
fixed

![delete user while active3 successful delete](https://cloud.githubusercontent.com/assets/20081753/17994682/7ad5bc12-6b8d-11e6-8020-f26ec201180d.png)

![delete user while active4 successful delete](https://cloud.githubusercontent.com/assets/20081753/17994688/853c2a42-6b8d-11e6-8610-7bba9bd6e66b.png)
