### ISSUE TITLE
Users - No Print/Export button displayed in the Edit User page

### ISSUE THREAD

**Issue by jparala** [junpaolo/ePrice-validation-testing#37]
Scenario:
In Edit User page, click Print/Export button to print or export the user details.

Observed Result:
No Print/Export button displayed in the page.

Expected Result:
Print/Export button is displayed in the edit user page.

Screenshot.
![pic8](https://cloud.githubusercontent.com/assets/21092654/17802641/0142a25c-6624-11e6-89b4-cd78678d47d8.JPG)

**Comment by vernonminer** [comment]
Same as #32

**Comment by junpaolo** [comment]
Considered as OOS
