### ISSUE TITLE
Home - There are criterion with blank selection

### ISSUE THREAD

**Issue by jparala** [junpaolo/ePrice-validation-testing#38]
Scenario:
In Home page, select any items in the fields.

Observed Result:
Some criterion have blank selections.

Question: Is this a defect?

Screenshots
<img width="817" alt="pic107" src="https://cloud.githubusercontent.com/assets/21092654/17802790/db7fd6ce-6624-11e6-8e2c-39a1832d6aaa.png">
<img width="816" alt="pic108" src="https://cloud.githubusercontent.com/assets/21092654/17802794/e0befad4-6624-11e6-88d6-55a722b91430.png">
<img width="821" alt="pic109" src="https://cloud.githubusercontent.com/assets/21092654/17802800/e5d33dc8-6624-11e6-93f7-9c12613261e6.png">
<img width="831" alt="pic110" src="https://cloud.githubusercontent.com/assets/21092654/17802803/e954e514-6624-11e6-99ba-c6a04b4bb002.png">

**Comment by vernonminer** [comment]
This is as designed. For those criteria a blank selection is valid.
