### ISSUE TITLE
PRODUCTS & GROUPS - Manage Products> Product List panel > Edit Product Details > Details Panel

### ISSUE THREAD

**Issue by coleenmarie** [junpaolo/ePrice-validation-testing#39]
**Scenario:** 
User will view product Details

**Observed Result:**
Was able to alter/modify made selection on all fields in the details panel in Edit Product Details 

**Expected Result:**
All of the fields in the details panel are displayed as read-only values. The values displayed are the selections that a user would make on the home search view for the specific field. 

![image](https://cloud.githubusercontent.com/assets/20077923/17828082/c667a1f4-66ba-11e6-904e-a2fc508a2dbb.png)

**Comment by vernonminer** [comment]
Updated Documentation. Users who can modify existing products can make changes to these fields.
