### ISSUE TITLE
Comparison Report - Badge count is set to 0 value

### ISSUE THREAD

**Issue by junpaolo** [junpaolo/ePrice-validation-testing#4]
**Scenario:**
User will validate the Comparison Report main page

**Steps:**
1. Click the Reports dropdown button from the navigation bar
2. Select Report List
3. Choose Comparison Report

**Observed Result:**
Product Group available items badge has a value of 0

**Expected Result:**
Each badge must reflect the total amount of items from the list

![product group available badge error always set to 0 at the main page](https://cloud.githubusercontent.com/assets/20081753/17762538/42bcdd5a-6544-11e6-8841-2ddb938e242e.png)

**Comment by vernonminer** [comment]
Corrected JavaScript Fle

**Comment by junpaolo** [comment]
still having the same experience
![comparison report error in badge](https://cloud.githubusercontent.com/assets/20081753/17925766/da6b6640-6a20-11e6-9c8e-4986405b1f9a.png)

**Comment by vernonminer** [comment]
Retest was done prior to application update

**Comment by junpaolo** [comment]
fixed
![Uploading Comparison report main page ok.png…]()
