### ISSUE TITLE
PRODUCTS & GROUPS - Edit Product Details > Product Group Details> Remove action button

### ISSUE THREAD

**Issue by coleenmarie** [junpaolo/ePrice-validation-testing#40]
**Scenario:** 
User granted with modify product group should able to remove product from the product group details panel. 

**Observed Result:**
Role: Administrator;  Privilege : Can modify product group
1. Clicking remove button was not able to remove product group
2. Clicking remove button, page number disappears. & Copy, Excel, Print button disappears. 
3. Clicking remove button, product list sorts to descending order
4. Semicolon in the lower left side. 
(Please see screenshots below)

**Expected Result:**
Remove product from the Product Group

![image](https://cloud.githubusercontent.com/assets/20077923/17828562/ed1d307c-66c7-11e6-9c3a-34e878e38020.png)

![image](https://cloud.githubusercontent.com/assets/20077923/17828553/91c87858-66c7-11e6-8851-b7d49c8c265c.png)

![image](https://cloud.githubusercontent.com/assets/20077923/17828567/0e60746a-66c8-11e6-8256-c729fbb3ea5c.png)

**Comment by vernonminer** [comment]
Corrected

**Comment by junpaolo** [comment]
Hi Vernon,

Can you assist me on how to execute this. I tried the same approach you told us in https://github.com/junpaolo/ePrice-validation-testing/issues/63 . Thanks

![how to execute remove product group](https://cloud.githubusercontent.com/assets/20081753/18119955/c0edbcbc-6f8f-11e6-94bf-ec50c0f5829c.png)

**Comment by vernonminer** [comment]
Updated documentation to match application

**Comment by junpaolo** [comment]
Unable to proceed. An error message was displayed after clicking the action button

![unable to remove product from product group1](https://cloud.githubusercontent.com/assets/20081753/18234894/8cdf7902-7344-11e6-9d89-72d6e415eab7.png)

![unable to remove product from product group](https://cloud.githubusercontent.com/assets/20081753/18234897/94cee1a2-7344-11e6-9805-1c25913625a0.png)

**Comment by vernonminer** [comment]
Still working on this one.

**Comment by vernonminer** [comment]
Corrected Controller Code.

**Comment by junpaolo** [comment]
fixed
![able to access edit product details page](https://cloud.githubusercontent.com/assets/20081753/18464249/6b38b140-79c2-11e6-9e6d-ed5d0306a5b9.png)
