### ISSUE TITLE
Benchmark Report - Help block not visible

### ISSUE THREAD

**Issue by junpaolo** [junpaolo/ePrice-validation-testing#41]
**Scenario:**
User will validate the help block section in Benchmark Report

**Steps:**
1. Navigate to Benchmark Report
2. Check each reports if the Help block is visible

**Observed Result:**
Help block not visible

**Expected Result:**
The Help block at the bottom is there to remind the user of how to use the criteria and what can be expected in the return.

![no help block](https://cloud.githubusercontent.com/assets/20081753/17828393/a92206ea-66c2-11e6-8c25-7e449d69a037.png)

**Comment by vernonminer** [comment]
Help blocks are optional for the display. If there is no content in the database it is not displayed. The documentation includes a discussion of the help block for completeness. Realistically, no help block should be expected until after the addition of the "Manage Content" option in the maintenance menu. That is where the administrators can provide content for the help blocks.
