### ISSUE TITLE
PRODUCTS & GROUPS - Manage Products> Product List panel > Edit Product Details > Product Group Details > Remove button 

### ISSUE THREAD

**Issue by coleenmarie** [junpaolo/ePrice-validation-testing#43]
**Scenario:** 
Error message is displayed when removing product from the product group fails

**Observed Result:**
No error message shown upon clicking remove action button

**Expected Result:**
Error message is displayed in red below the action buttons

![image](https://cloud.githubusercontent.com/assets/20077923/17828487/ab806488-66c5-11e6-824a-94d390e3003b.png)

**Comment by junpaolo** [comment]
fixed
![edit product details_remove from product group1](https://cloud.githubusercontent.com/assets/20081753/18119594/0175cb6e-6f8e-11e6-8c59-fb20ecc4c19e.png)

![edit product details_remove from product group4](https://cloud.githubusercontent.com/assets/20081753/18119607/0a1990f2-6f8e-11e6-8654-7a1c553c871d.png)
