### ISSUE TITLE
Ranking Report - Help block not visible

### ISSUE THREAD

**Issue by junpaolo** [junpaolo/ePrice-validation-testing#44]
**Scenario:**
User will validate the help block section in Ranking Report

**Steps:**
1. Navigate to Ranking Report
2. Check each reports if the Help block is visible

**Observed Result:**
Help block not visible

**Expected Result:**
The Help block at the bottom is there to remind the user of how to use the criteria and what can be expected in the return.

![clear button](https://cloud.githubusercontent.com/assets/20081753/17828529/e905e76e-66c6-11e6-95bd-270ae42afd36.png)

**Comment by vernonminer** [comment]
Help blocks are optional for the display. If there is no content in the database it is not displayed. The documentation includes a discussion of the help block for completeness. Realistically, no help block should be expected until after the addition of the "Manage Content" option in the maintenance menu. That is where the administrators can provide content for the help blocks.
