### ISSUE TITLE
PRODUCTS & GROUPS - Manage Products  > Help Block 

### ISSUE THREAD

**Issue by coleenmarie** [junpaolo/ePrice-validation-testing#46]
**Scenario:** 
Help Block in Manage Products
**Observed Result:**
Help lock is not visible
**Expected Result:**
Help Block should be available

![product-008](https://cloud.githubusercontent.com/assets/20077923/17828748/4e989904-66cd-11e6-958c-3043591859cf.png)

**Comment by vernonminer** [comment]
Help blocks are optional for the display. If there is no content in the database it is not displayed. The documentation includes a discussion of the help block for completeness. Realistically, no help block should be expected until after the addition of the "Manage Content" option in the maintenance menu. That is where the administrators can provide content for the help blocks.
