### ISSUE TITLE
PRODUCTS & GROUPS - Manage Products> Product List panel > Edit Product Details 

### ISSUE THREAD

**Issue by coleenmarie** [junpaolo/ePrice-validation-testing#47]
Approval/ Rejection Comment field in Edit Product Details is available and disabled.  but not defined in the developer's notebook.

**Comment by vernonminer** [comment]
Approve or Reject comment should only be displayed for products that have an approved or rejected status.

**Comment by junpaolo** [comment]
Since there's no available products that have an approved or rejected status, we will consider this as OOS
