### ISSUE TITLE
Pricel list and groups - ajax error

### ISSUE THREAD

**Issue by jtolen** [junpaolo/ePrice-validation-testing#5]
Scenario: 
Saving price list Max discount changes

Observed Result:
Does not save changes due to ajax error 

Expected Result:
Changes will be saved without errors

Test Steps:
1. Choose any price list name
2. Input a valid amount
3. Click Save button

![10](https://cloud.githubusercontent.com/assets/19830714/17763850/0375704e-654e-11e6-9b60-4dff0b2fbdc5.png)

**Comment by vernonminer** [comment]
Updated Stored Procs in PMReport DB and update DBContext in application

**Comment by junpaolo** [comment]
fixed
![edit max discount](https://cloud.githubusercontent.com/assets/20081753/18080207/15141580-6ec7-11e6-8a63-5bfb8f98bde2.png)

![edit max discount2](https://cloud.githubusercontent.com/assets/20081753/18080212/1ef7cfd8-6ec7-11e6-9617-3b8393f23ff9.png)
