### ISSUE TITLE
PRODUCTS & GROUPS - Manage Products > Product List >Edit Product Details

### ISSUE THREAD

**Issue by coleenmarie** [junpaolo/ePrice-validation-testing#50]
Was not able to view in read-only mode because was not able to change role as guest
The following fields are that needs to view in read-only: 
Product List, Product code, Product comment, Price Multiplier, Cost, Activate Status Yes/No switch in Products & Groups - Product List

**Comment by vernonminer** [comment]
User roles can now be changed.

**Comment by junpaolo** [comment]
Hi Vernon,

Can you assist us on how to execute this one. I changed the user role to approver and I turned off the modify products privilege. It displays this message after I try to access the Manage Products:

![manage product view only mode2](https://cloud.githubusercontent.com/assets/20081753/18117869/fe10825c-6f83-11e6-9523-4489d9f178a5.png)

![manage product view only mode1](https://cloud.githubusercontent.com/assets/20081753/18117864/f5df8740-6f83-11e6-8ca6-980d9943e384.png)

**Comment by vernonminer** [comment]
The manage products menu option displays to anyone that has either of these privileges.

Modify Products
Delete Products.

Normally a user would not be able to delete products and not modify them. Both approver and administrator roles can have these privileges.

The modify products view was restricted to only those users that have modify products privilege. Now it will also display to users with delete products privilege the same as the menu option.

**Comment by junpaolo** [comment]
will consider this as out of scope
