### ISSUE TITLE
Test data needed

### ISSUE THREAD

**Issue by junpaolo** [junpaolo/ePrice-validation-testing#51]
**Users** 
-dummy log in name. need this to create a new user

**Products and Groups**
-price multiplier
-product code

**Comment by vernonminer** [comment]
Price Multiplier is collected from web configuration file. There is a PriceMultiplierValue field in the records of the Product table. 

The Product Code is only used in 240 products and none are active. Assume it is a relic from previous revision.

**Comment by junpaolo** [comment]
Hi Vernon,

Can you give us a Login Name for us to be able to create a new user?

**Comment by junpaolo** [comment]
Pls disregard this one
