### ISSUE TITLE
PRODUCTS & GROUPS - Edit Product Details > Update button

### ISSUE THREAD

**Issue by coleenmarie** [junpaolo/ePrice-validation-testing#52]
**Scenario:** 
update a product

**Observed Result:**
Clicking update button encountered error message:  "Server model error" 

**Expected Result:**
Able to update changes applied to the product details. 

![image](https://cloud.githubusercontent.com/assets/20077923/17829119/c914156a-66d6-11e6-8989-7674ce6e9a5d.png)

**Comment by junpaolo** [comment]
Still experiencing the same error. Error message has changed

![edit product details failed](https://cloud.githubusercontent.com/assets/20081753/18119233/3eff6da2-6f8c-11e6-9a67-2f95eb0c7dcb.png)

**Comment by vernonminer** [comment]
Still working on this one.

**Comment by vernonminer** [comment]
Corrected Controller Code.

**Comment by junpaolo** [comment]
Unable to update product details. Error message displayed

![edit product details failed](https://cloud.githubusercontent.com/assets/20081753/18464369/3da24164-79c3-11e6-8f86-c2ec2c1a8b7b.png)

**Comment by vernonminer** [comment]
Corrected validation code in Controller

**Comment by junpaolo** [comment]
The product is duplicating each time I update the product
![manage product error1](https://cloud.githubusercontent.com/assets/20081753/18496646/0d3e9a94-7a5a-11e6-8a3e-3a8fb1ea2178.png)

Error message appears when I tried to edit again the same product for the 3rd time
![manage product error2](https://cloud.githubusercontent.com/assets/20081753/18496657/347917ce-7a5a-11e6-91b6-268147f9ffed.png)

**Comment by vernonminer** [comment]
The products are NOT duplicating. The stored procedure that builds the list was duplicating the records because of a join with the product status table. I removed the join.

**Comment by junpaolo** [comment]
Unable to search product
![unable to search product](https://cloud.githubusercontent.com/assets/20081753/18576476/7d18f420-7c14-11e6-9b1d-5bdfb5079798.png)

**Comment by vernonminer** [comment]
Corrected product search.

**Comment by junpaolo** [comment]
It seems that I can successfully edit product
![edit product details1](https://cloud.githubusercontent.com/assets/20081753/18653724/67d6baa0-7f0e-11e6-8060-59afa136e17d.png)

But when I try to edit the same product again an error message appears
![edit product details2 error](https://cloud.githubusercontent.com/assets/20081753/18653739/8007ae54-7f0e-11e6-800e-d809891e4bb2.png)

**Comment by junpaolo** [comment]
Pass with comments

"When updating product groups  there is a stored procedure that is called when a new product is created or the product details are updated that assigns product groups. So the product groups list may not reflect the expected results. See this stored procedure for details

spProductGroupProductAssign"
