### ISSUE TITLE
PRODUCTS & GROUPS - Manage Product Groups > Product Group List panel

### ISSUE THREAD

**Issue by coleenmarie** [junpaolo/ePrice-validation-testing#53]
Observed Result:
"undefined " is visible on top of copy, excel, print buttons 
Expected Result:
There should be no "undefined " on top of copy, excel, print buttons 

![image](https://cloud.githubusercontent.com/assets/20077923/17829182/09cc642a-66d9-11e6-97f0-587a6625f7ee.png)

**Comment by vernonminer** [comment]
Corrected JavaScript file

**Comment by junpaolo** [comment]
fixed
![no undefined in manage product group search](https://cloud.githubusercontent.com/assets/20081753/18118888/3615a0c8-6f8a-11e6-92c1-23224f91f45a.png)
