### ISSUE TITLE
PRODUCTS & GROUPS - Manage Product Groups

### ISSUE THREAD

**Issue by coleenmarie** [junpaolo/ePrice-validation-testing#54]
**Scenario:** 
Allows user to specify text in the Sub Product Group Text to search

**Observed Result:**
Did not return "correct" search results on Sub Product Group text

**Expected Result:**
Should able to return search result 

![image](https://cloud.githubusercontent.com/assets/20077923/17830862/d861d5f4-670b-11e6-847e-56eed5b8ce4b.png)

**Comment by vernonminer** [comment]
Corrected Stored Procedure

**Comment by junpaolo** [comment]
fixed
![managa product subproduct group text search](https://cloud.githubusercontent.com/assets/20081753/17999409/c3ff0e2a-6bab-11e6-8f43-77ddb4eca7e9.png)
