### ISSUE TITLE
PRODUCTS & GROUPS - Manage Product Groups > Product Text - "Test Data"

### ISSUE THREAD

**Issue by coleenmarie** [junpaolo/ePrice-validation-testing#55]
**Scenario:**  
User inputs value on Product Text field. Should the search result be based on the value inputted in the Product Text field if Yes, search result is incorrect. 

If No, search result returns depends on its category - Group Code or Group Text. Test data will be needed to validate this.  (Provide test data)

**Observed Result:** 
Was able to display search in progress but could NOT validate returned search result is correct - Test Data needed

**Expected Result:** 
Return search results

![image](https://cloud.githubusercontent.com/assets/20077923/17838179/f175f776-67f8-11e6-89ec-1e7f27a726d0.png)

**Comment by vernonminer** [comment]
You can execute a query in the SQL Server Management Studio in the PMOperation database to verify returned data.

**Comment by vernonminer** [comment]
When using product text in product group search the results returned should be a list of product groups that have at least one associated product that contains the input product text.
