### ISSUE TITLE
PRODUCTS & GROUPS - Manage Product Groups > Search result on null fields 

### ISSUE THREAD

**Issue by coleenmarie** [junpaolo/ePrice-validation-testing#56]
**Scenario:**
Left all fields blank to search all products 

**Observed Result:** 
Search result was not able to return all available data and "undefined" appeared after loading search in the Product Group List panel 

**Expected Result:** 
Search result returns list  all products 

![image](https://cloud.githubusercontent.com/assets/20077923/17838244/dc67475c-67fa-11e6-975b-59de0333ab28.png)

**Comment by vernonminer** [comment]
There are too many product to display in the list when searching with no criteria. I added an error message display to the JavaScript file to require at least one criterion.

![image](https://cloud.githubusercontent.com/assets/15823308/17903118/edfdc3fc-692f-11e6-9fae-063d1a5c7dfe.png)

**Comment by junpaolo** [comment]
Still experiencing the same issue
![manage product groups search all null](https://cloud.githubusercontent.com/assets/20081753/17998274/143cb064-6ba6-11e6-8ef1-38c801e4b2bd.png)

**Comment by vernonminer** [comment]
Please make sure to force the browser to download new JavaScript files for the page prior to retesting. Pressing F5 key should do it.

**Comment by junpaolo** [comment]
fixed
![manage products require 1 mandatory field](https://cloud.githubusercontent.com/assets/20081753/18117022/aa16f7a8-6f7e-11e6-86e7-4c4da29bb958.png)
