### ISSUE TITLE
PRODUCTS & GROUPS - Manage Product Groups > Product Group List panel > Excel button 

### ISSUE THREAD

**Issue by coleenmarie** [junpaolo/ePrice-validation-testing#57]
**Scenario:**
Export to excel spreadsheet

**Observed Result:** 
Was not able to export entire result "Status" to the excel sheet

**Expected Result:** 
Export entire result to excel spreadsheet

![image](https://cloud.githubusercontent.com/assets/20077923/17838354/1a24fb18-67fe-11e6-83f0-45dce29fe331.png)

![image](https://cloud.githubusercontent.com/assets/20077923/17838355/2f728b16-67fe-11e6-8d6b-bc5608d166aa.png)

**Comment by vernonminer** [comment]
Added new span to partial view with "visible-print" class to show Active or Inactive for status value when printing or exporting

**Comment by junpaolo** [comment]
fixed
![manage product groups excel button](https://cloud.githubusercontent.com/assets/20081753/17996778/84136530-6b9d-11e6-8094-50f9f9eab260.png)
