### ISSUE TITLE
PRODUCTS & GROUPS - Manage Product Groups > Product Group List panel > Copy button

### ISSUE THREAD

**Issue by coleenmarie** [junpaolo/ePrice-validation-testing#59]
**Scenario:**
Copy to clipboard entire result

**Observed Result:** 
Was able to copy to clipboard but was not able to export entire result "Status" to the word document

**Expected Result:** 
Paste copied in the clipboard to any chosen application

![image](https://cloud.githubusercontent.com/assets/20077923/17838821/ce96745a-6808-11e6-8776-51802f5707b9.png)

![image](https://cloud.githubusercontent.com/assets/20077923/17838828/f648dd76-6808-11e6-80ac-93c16218fe11.png)

**Comment by vernonminer** [comment]
Added new span to partial view with "visible-print" class to show Active or Inactive for status value when printing or exporting

**Comment by junpaolo** [comment]
fixed

![manage product groups copy button](https://cloud.githubusercontent.com/assets/20081753/17995444/67375042-6b94-11e6-97f9-8de4247a42dd.png)
