### ISSUE TITLE
Price list and groups - ajax error

### ISSUE THREAD

**Issue by jtolen** [junpaolo/ePrice-validation-testing#6]
Scenario: 
Activate Price List changes

Observed Result:
Does not save changes due to ajax error

Expected Result:
Changes will be saved without errors

Test Steps:
1. Select items to activate
3. Click Save button

![17](https://cloud.githubusercontent.com/assets/19830714/17764480/286b4e10-6552-11e6-9d3f-cbd5762e5bfd.png)

**Comment by vernonminer** [comment]
Updated Stored Procs in PMReport DB and update DBContext in application

**Comment by junpaolo** [comment]
Still experiencing the same issue
![activate pricelist error](https://cloud.githubusercontent.com/assets/20081753/18114542/6669b298-6f6a-11e6-9722-60e6da4c1ce9.png)

**Comment by vernonminer** [comment]
Updated Controller code

**Comment by junpaolo** [comment]
fixed

![activate price list successful1](https://cloud.githubusercontent.com/assets/20081753/18235101/19050a92-7349-11e6-9d2c-50045aad573b.png)

![activate price list successful2](https://cloud.githubusercontent.com/assets/20081753/18235108/33af1ae0-7349-11e6-8c7f-8f5bd61d36d0.png)
