### ISSUE TITLE
PRODUCTS & GROUPS - Manage Product Groups > Product Group List panel > Print button

### ISSUE THREAD

**Issue by coleenmarie** [junpaolo/ePrice-validation-testing#61]
Scenario:
Create printable entire result

Observed Result: 
Was able to  export entire result "Status" to the printable version

Expected Result: 
Print entire result. 

![image](https://cloud.githubusercontent.com/assets/20077923/17838945/4fe8f25a-680c-11e6-854c-a4bcdb62c238.png)

**Comment by vernonminer** [comment]
Added new span to partial view for status with class of "visible-print" to show Active or Inactive in status cell.

**Comment by junpaolo** [comment]
fixed
![manage product groups print button](https://cloud.githubusercontent.com/assets/20081753/17995376/ba93c528-6b93-11e6-9f70-18a07ba3df1f.png)
