### ISSUE TITLE
QUERY - Unable to delete inactive query

### ISSUE THREAD

**Issue by junpaolo** [junpaolo/ePrice-validation-testing#62]
Scenario:
User will try to delete an inactive query

Steps:
1. Set your query first to inactive
2. Click delete button

Observed Result:
Unable to delete 

Expected Result:
Deleting inactive query successful

![delete an inactive status failed](https://cloud.githubusercontent.com/assets/20081753/17841768/b853a64a-684e-11e6-8081-05330dd8c82c.png)

**Comment by vernonminer** [comment]
Deleting a query with active status = true will deactivate the query. Deleting a query with active status = false will remove the query from the database. Active status used to determine process is read from DB. Therefore, the process described above requires the user to click on the "Delete" button twice. The first time will set the active status in the DB to inactive, the second would remove it from the database. 

Coded this way specifically to prevent removing active queries from DB in a single click.

Update of stored proc in DB that updates the query cleared the displayed error.

**Comment by junpaolo** [comment]
Hi Vernon,

Still experiencing the same issue sir. Please refer below:

![delete inactive query error](https://cloud.githubusercontent.com/assets/20081753/17876968/a4dde846-6911-11e6-8847-44a736d22525.png)

**Comment by vernonminer** [comment]
The QA application will be updated at end of business Tuesday 8/23. No retesting should be done prior to that.

**Comment by junpaolo** [comment]
still having the same experience
![unable to delete inactive query](https://cloud.githubusercontent.com/assets/20081753/17925593/19683554-6a20-11e6-91ad-750bd81361a9.png)

**Comment by vernonminer** [comment]
Retested prior to application update.

**Comment by junpaolo** [comment]
fixed

![delete inactive query1](https://cloud.githubusercontent.com/assets/20081753/17991640/071bc2f4-6b73-11e6-84e2-17be60d515f8.png)

![delete inactive query2](https://cloud.githubusercontent.com/assets/20081753/17991643/0deba748-6b73-11e6-9a33-da99e9cd2af9.png)
