### ISSUE TITLE
Products and Groups - how to execute

### ISSUE THREAD

**Issue by junpaolo** [junpaolo/ePrice-validation-testing#63]
Hi Vernon,

Seeking assistance on how to execute this. Thanks.

![how to execute](https://cloud.githubusercontent.com/assets/20081753/17845716/8f555acc-6876-11e6-83ff-49824649f959.png)

**Comment by vernonminer** [comment]
Clicking on the "Pencel" action button will attempt to load the product group. The displayed example would occur if there was an issue reading the selected product group from the database. (For example another user deletes the product group.)
