### ISSUE TITLE
Query - INACTIVE public query visible in my private query

### ISSUE THREAD

**Issue by junpaolo** [junpaolo/ePrice-validation-testing#64]
**Scenario:**
User will view his inactive private queries

**Observed Result:**
Public query visible in my private queries

**Expected Result:**
The list will display my inactive private queries

![public query visible in my private queries](https://cloud.githubusercontent.com/assets/20081753/17876750/8c9294fa-690f-11e6-9d48-bf9b582bbcf3.png)

**Comment by vernonminer** [comment]
Stored procedure error. Applied additional filter in controller code.

**Comment by junpaolo** [comment]
still having the same experience
![inactive public query visible in my private](https://cloud.githubusercontent.com/assets/20081753/17925205/91ec2c62-6a1e-11e6-9c91-aaa16c30fcdf.png)

**Comment by vernonminer** [comment]
Retested prior to application update.

**Comment by junpaolo** [comment]
fixed

![public query display](https://cloud.githubusercontent.com/assets/20081753/17991004/7b9d7164-6b6d-11e6-8a4a-19cc0469f9de.png)
