### ISSUE TITLE
User - search and view clarification

### ISSUE THREAD

**Issue by junpaolo** [junpaolo/ePrice-validation-testing#67]
Hi Vernon,

The user if admin, can search and edit existing user. The view only option is not applicable. Please confirm

![view user](https://cloud.githubusercontent.com/assets/20081753/17929163/40e8b584-6a31-11e6-9d0c-45928dc11e79.png)

**Comment by vernonminer** [comment]
Any user cannot modify their own profile. Therefore, an administrator can only view their profile, this is view only mode.

**Comment by junpaolo** [comment]
Print/Export button should not be visible. Please confirm

**Comment by vernonminer** [comment]
Correct
