### ISSUE TITLE
QUERY - Delete an ACTIVE query

### ISSUE THREAD

**Issue by junpaolo** [junpaolo/ePrice-validation-testing#68]
Scenario:
User will delete a query with an active status
![delete active query 1](https://cloud.githubusercontent.com/assets/20081753/17991478/8e073f3e-6b71-11e6-8a83-337c75ae33f2.png)

Observed Result:
After clicking the delete button, system displayed an error page
![delete active query 2 after clicking the delete button](https://cloud.githubusercontent.com/assets/20081753/17991463/79ad9628-6b71-11e6-9bc5-d3c15cc66b35.png)

Expected Result:
Deleting an active query will set the query to inactive. User will be redirected to query main page

**Comment by vernonminer** [comment]
User is NOT redirected when deleting an Active query. The query is deactivated and this is displayed.

![image](https://cloud.githubusercontent.com/assets/15823308/18067014/8c3e170e-6e00-11e6-9ae3-e2c55e1aea37.png)

**Comment by junpaolo** [comment]
fixed

![delete active query1](https://cloud.githubusercontent.com/assets/20081753/18079050/5b4e80d6-6ec1-11e6-84b7-8fd86f88a36a.png)

![delete active query2](https://cloud.githubusercontent.com/assets/20081753/18079056/627432e8-6ec1-11e6-8b77-30b00890bcae.png)
