### ISSUE TITLE
HOME - Ajax error displayed when searching

### ISSUE THREAD

**Issue by junpaolo** [junpaolo/ePrice-validation-testing#69]
Scenario:
User will search in home page

Observed result:
Ajax error displayed

Expected Result:
Search successful

![ajax error when searching in home](https://cloud.githubusercontent.com/assets/20081753/17991955/c0d2595e-6b75-11e6-9907-9b4c88a97252.png)

**Comment by vernonminer** [comment]
I corrected the JavaScript file again. Please make sure you force the application to download new JavaScript files on each page when you retest. Pressing the F5 key to force a page refresh should do it.

**Comment by junpaolo** [comment]
fixed
![home search from loaded query](https://cloud.githubusercontent.com/assets/20081753/18079623/4d21ce34-6ec4-11e6-945e-165d289d58ee.png)
