### ISSUE TITLE
Price List and groups - ajax error

### ISSUE THREAD

**Issue by jtolen** [junpaolo/ePrice-validation-testing#7]
Scenario: 
Deactivate price List changes

Observed Result:
Does not save changes due to ajax error

Expected Result:
Changes will be saved without errors

Test Steps:
1. Select item to deactivate
2. Click Save button

![24](https://cloud.githubusercontent.com/assets/19830714/17764755/03bf4268-6554-11e6-8e16-8e24b1055595.png)

**Comment by vernonminer** [comment]
Updated Stored Procs in PMReport DB and update DBContext in application

**Comment by junpaolo** [comment]
Still experiencing the same issue
![deactivate pricelist error](https://cloud.githubusercontent.com/assets/20081753/18114488/05f54b98-6f6a-11e6-8264-bb8e1a11a82d.png)

**Comment by vernonminer** [comment]
Updated Controller code

**Comment by junpaolo** [comment]
fixed
![deactivate pricelist1](https://cloud.githubusercontent.com/assets/20081753/18235180/33e6bf8a-734a-11e6-971b-26ae42a1372b.png)

![deactivate pricelist2](https://cloud.githubusercontent.com/assets/20081753/18235181/3b5f3756-734a-11e6-84d6-f929cba0a8dc.png)

![deactivate pricelist3](https://cloud.githubusercontent.com/assets/20081753/18235183/4175c560-734a-11e6-8cb5-1e5149938dc0.png)
