### ISSUE TITLE
Query - Saving changes PUBLIC query

### ISSUE THREAD

**Issue by junpaolo** [junpaolo/ePrice-validation-testing#70]
Scenario:
I edit the public query. I make sure that all fields have values. I also switched all status to NO. 

Observed Result:
Some fields does not save the changes I made

Sub pricelist
![public subprice list](https://cloud.githubusercontent.com/assets/20081753/17994175/0b181ea0-6b89-11e6-956e-d8271a231c1f.png)

Commercial brand has the loading icon visible 
![commercial brand](https://cloud.githubusercontent.com/assets/20081753/17994225/2f2f37ba-6b89-11e6-94b9-58c511bda96b.png)

Expand manufacturer
![expand manufacturer](https://cloud.githubusercontent.com/assets/20081753/17994233/40c59bea-6b89-11e6-9cb4-f37812998560.png)

Active switch images are not as I expected

**Comment by vernonminer** [comment]
Corrected JavaScript file

**Comment by junpaolo** [comment]
fixed
![saving changes query public](https://cloud.githubusercontent.com/assets/20081753/18079332/a413994a-6ec2-11e6-8bf4-f3c14bffd5a4.png)
