### ISSUE TITLE
USER - Clear button 

### ISSUE THREAD

**Issue by junpaolo** [junpaolo/ePrice-validation-testing#72]
**Scenario:**
User will click the clear button after searching a specific user

**Observed Result:**
Clears only the search text boxes
![user menu clear button error](https://cloud.githubusercontent.com/assets/20081753/18071943/429dbe56-6e8c-11e6-8006-78457bee0591.png)

**Expected** Result:
Clicking the clear button will clear all text boxes and search results

**Comment by vernonminer** [comment]
Corrected JavaScript file.

**Comment by junpaolo** [comment]
Still experiencing the same issue
![user clear button error](https://cloud.githubusercontent.com/assets/20081753/18117130/42376234-6f7f-11e6-9fd0-34880f409424.png)

**Comment by junpaolo** [comment]
fixed

![user_clear button1](https://cloud.githubusercontent.com/assets/20081753/18163352/1787b68a-706d-11e6-87df-fafe0340f57e.png)

![user_clear button2](https://cloud.githubusercontent.com/assets/20081753/18163357/1ea8b7fc-706d-11e6-84aa-d1ac804adf16.png)
