### ISSUE TITLE
Manage Pricelist Groups - Unable to search Pricelist Group 

### ISSUE THREAD

**Issue by junpaolo** [junpaolo/ePrice-validation-testing#73]
Scenario:
User will search for pricelist group

Observed Result:
Unable to search

Expected Result:
User can successfully search  a pricelist group

![search pricelist group failed](https://cloud.githubusercontent.com/assets/20081753/18122436/1d6636a2-6f9c-11e6-855e-58dce2c0be54.png)

**Comment by vernonminer** [comment]
Controller code correction.

**Comment by junpaolo** [comment]
fixed

![search pricelist group](https://cloud.githubusercontent.com/assets/20081753/18160753/68e2b734-7061-11e6-836c-9ea47101757d.png)
