### ISSUE TITLE
Create Price Lists Group - Duplicating 

### ISSUE THREAD

**Issue by junpaolo** [junpaolo/ePrice-validation-testing#74]
Scenario:
User will create a price list group

Observed Result:
Created price list group is duplicating when clicking the save button multiple times

Expected Result:
Will not duplicate the created price list group when clicking the save button multiple times

![duplicating created pricelist group](https://cloud.githubusercontent.com/assets/20081753/18123699/a0cf9704-6fa1-11e6-8e28-ba65c7d6b6c9.png)

**Comment by vernonminer** [comment]
Cannot reproduce. 
1. Selected create new price list group from menu
2. Input name of price list group that already exists and correctly received this displayed error

![image](https://cloud.githubusercontent.com/assets/15823308/18139632/eadcc544-6f77-11e6-839a-de64f2053f2f.png)
1. Input new price list group name
2. Added comment
3. Clicked Save button and results were

![image](https://cloud.githubusercontent.com/assets/15823308/18139731/42a5b90c-6f78-11e6-80b8-dfb89acf0136.png)
1. Clicked Save button again and results were

![image](https://cloud.githubusercontent.com/assets/15823308/18139777/6f404ed2-6f78-11e6-840a-19d326a75d51.png)

**Comment by junpaolo** [comment]
fixed

![create pricelist group duplicating fixed](https://cloud.githubusercontent.com/assets/20081753/18157862/6b747438-7052-11e6-9a31-0c334cd399b5.png)
