### ISSUE TITLE
Manage Pricelist Groups - Unable to update price list group

### ISSUE THREAD

**Issue by junpaolo** [junpaolo/ePrice-validation-testing#75]
Scenario:
User will update a price list group

Observed Result:
Update unsuccessful

Expected Result:
Update successful

![update unsuccessful1](https://cloud.githubusercontent.com/assets/20081753/18125633/e97eeff6-6fa9-11e6-9c54-812d49e3e2bf.png)

![update unsuccessful2](https://cloud.githubusercontent.com/assets/20081753/18125639/f07ae9b8-6fa9-11e6-90ba-cca98b999321.png)

**Comment by vernonminer** [comment]
Displayed list of available price lists was displaying all price lists and it should have been only active price lists. Selections that were made to add to price list group were all inactive price lists. The selected price list was correctly displaying only active price lists. Therefore, it appeared the update was not occurring as reported back to the user.

Corrected code to display only active price lists in the available list.

**Comment by junpaolo** [comment]
fixed
![update pricelist group1](https://cloud.githubusercontent.com/assets/20081753/18157729/b9c819ce-7051-11e6-95e9-a00542bf286c.png)

![update pricelist group2](https://cloud.githubusercontent.com/assets/20081753/18157734/c1b52bea-7051-11e6-98ea-213de0c4192c.png)
