### ISSUE TITLE
PRODUCTS & GROUPS - Manage Product Groups > Clear Search result 

### ISSUE THREAD

**Issue by coleenmarie** [junpaolo/ePrice-validation-testing#76]
Scenario: 
Clear search result by clicking clear button after search returned result.

Observed Result:
Was able to return results but upon clicking clear button  "undefined" text appeared on top of the Copy Excel Print buttons

Expected Results: 
Should able to clear all parameters without error

![image](https://cloud.githubusercontent.com/assets/20077923/18151754/1b0a0ab8-7024-11e6-8432-f60b9102fe51.png)

**Comment by vernonminer** [comment]
JavaScript file correction

**Comment by junpaolo** [comment]
fixed
![clear button search product group](https://cloud.githubusercontent.com/assets/20081753/18200198/4300a8c0-7136-11e6-8245-c99caf0d8800.png)
