### ISSUE TITLE
Manage Pricelist Groups - Unable to search Pricelist Group using "Included Price Lists" only

### ISSUE THREAD

**Issue by junpaolo** [junpaolo/ePrice-validation-testing#77]
**Scenario:**
User will search using Included Price Lists only

**Observed Result:**
Search unsuccessful

**Expected Result:**
User is able to search using Included Price Lists only

![unable to search using included price lists only](https://cloud.githubusercontent.com/assets/20081753/18161585/20c95850-7065-11e6-9f05-783a5ea50230.png)

**Comment by vernonminer** [comment]
Updated Controller code

**Comment by junpaolo** [comment]
fixed

![search pricelist group using included pricelists only](https://cloud.githubusercontent.com/assets/20081753/18188699/b7c9cefc-70e6-11e6-8884-afaec5358688.png)
