### ISSUE TITLE
Manage Pricelist Groups - Search Pricelist Groups - Clear button

### ISSUE THREAD

**Issue by junpaolo** [junpaolo/ePrice-validation-testing#78]
Scenario:
User will click the clear button after searching a pricelist group

Observed Result:
Pop up message displays

Expected Result:
Clicking the clear button will clear all search criterion and search results

![message displayed when clicking the cancel button_manage pricelist group search](https://cloud.githubusercontent.com/assets/20081753/18161971/c3194542-7066-11e6-8393-a2eef9156179.png)

**Comment by vernonminer** [comment]
Updated JavaScript file

**Comment by junpaolo** [comment]
fixed
![search pricelist group and clear button1](https://cloud.githubusercontent.com/assets/20081753/18188437/c5b0135c-70e4-11e6-8a4f-754b90bcd6ed.png)

![search pricelist group and clear button2](https://cloud.githubusercontent.com/assets/20081753/18188441/cf8a81f0-70e4-11e6-900c-c6ac5b863c02.png)
