### ISSUE TITLE
Manage Pricelist Groups - Search Pricelist Groups - Edit Pricelist Group details

### ISSUE THREAD

**Issue by junpaolo** [junpaolo/ePrice-validation-testing#79]
**Scenario:**
User will search a pricelist group and edit its details

**Observed Result:**
Edit details unsuccessful. An error message was displayed

**Expected Result:**
User is able to edit the pricelist group details

![edit pricelist group details error](https://cloud.githubusercontent.com/assets/20081753/18162796/7ad27c78-706a-11e6-9691-ad09ba31bd49.png)

**Comment by vernonminer** [comment]
updated controller method and database stored procedures

**Comment by junpaolo** [comment]
fixed

![edit pricelist group details1](https://cloud.githubusercontent.com/assets/20081753/18188332/f40db9e4-70e3-11e6-8055-e9feb08db2f7.png)

![edit pricelist group details2](https://cloud.githubusercontent.com/assets/20081753/18188338/ff190366-70e3-11e6-88d5-c3a2700e1c70.png)
