### ISSUE TITLE
Price List and groups - Ajax Error

### ISSUE THREAD

**Issue by jtolen** [junpaolo/ePrice-validation-testing#8]
Scenario: 
Rename price List

Observed Result:
Does not save changes due to ajax error

Expected Result:
Changes will be saved without errors

Test Steps:
1. Select price list to rename
2. Click Save button

![27](https://cloud.githubusercontent.com/assets/19830714/17764948/75a0660e-6555-11e6-98b7-c5626496281f.png)

**Comment by vernonminer** [comment]
Updated Stored Procs in PMReport DB and update DBContext in application

**Comment by junpaolo** [comment]
fixed
![loading while renaming pricelist successful](https://cloud.githubusercontent.com/assets/20081753/18114368/2be5c7f2-6f69-11e6-913f-b2df8e14fd62.png)

![loading while renaming pricelist successful2](https://cloud.githubusercontent.com/assets/20081753/18114373/36881f48-6f69-11e6-8b6b-6de176af1c69.png)
