### ISSUE TITLE
Products and Groups - Manage Products error

### ISSUE THREAD

**Issue by junpaolo** [junpaolo/ePrice-validation-testing#80]
Scenario:
User will access Manage Products

Observed Results:
Unable to access. Error message was displayed

Expected Result:
User can access Manage Products

![manage product not available](https://cloud.githubusercontent.com/assets/20081753/18199538/4c8c79a8-7133-11e6-9984-223ccdb7ad49.png)

**Comment by vernonminer** [comment]
For an unknown reason entity framework changed the return from a stored procedure to not match the real return structure. I updated the DBContext again to correct it.

**Comment by junpaolo** [comment]
Still experiencing the same issue

![unable to access manage product group](https://cloud.githubusercontent.com/assets/20081753/18235331/4d74b5a4-734c-11e6-86a8-c36abeed2db1.png)

**Comment by vernonminer** [comment]
It appears my last corrections did not get published. I published again.

**Comment by junpaolo** [comment]
fixed

![products and groups menu working](https://cloud.githubusercontent.com/assets/20081753/18295575/1ec499e2-74d5-11e6-9337-7874675cf593.png)

![products and groups menu working2](https://cloud.githubusercontent.com/assets/20081753/18295596/4c1ac02e-74d5-11e6-9020-a9111bebe7a2.png)

![products and groups menu working3](https://cloud.githubusercontent.com/assets/20081753/18295613/70157c26-74d5-11e6-9045-501c35c3d86e.png)
