### ISSUE TITLE
Manage Pricelist - Search Pricelist

### ISSUE THREAD

**Issue by junpaolo** [junpaolo/ePrice-validation-testing#81]
**Scenario:**
User will search for a Price list

**Observed Result:**
Retrieving XXX data rows. Please wait... is still visible after successfully loading all data

**Expected Result:**
Notification message should not be visible after successful loading of all data

![search pricelist please wait message still visible after successful loading](https://cloud.githubusercontent.com/assets/20081753/18199652/e493263e-7133-11e6-8542-7faa3aefbf73.png)

**Comment by vernonminer** [comment]
I wouldn't classify this as a bug. I updated the JavaScript file.

**Comment by junpaolo** [comment]
Experience is still the same
![please wait visible after searching a price lsit](https://cloud.githubusercontent.com/assets/20081753/18235356/aff56e30-734c-11e6-86a8-8b884144dce3.png)

**Comment by vernonminer** [comment]
Updated JavaScript file again.

**Comment by junpaolo** [comment]
fixed

![search price list without please wait message](https://cloud.githubusercontent.com/assets/20081753/18295432/f64edf82-74d3-11e6-82ab-e888afeec99b.png)
