### ISSUE TITLE
Price List and Groups - Clear button (search)

### ISSUE THREAD

**Issue by jtolen** [junpaolo/ePrice-validation-testing#9]
Scenario:
Click Clear button with Active search input criteria and results

Observed Result: 
Input criteria was cleared but not the Previous search results

Expected Result:
Input criteria and previous search results will be cleared

Test Steps:
Click Clear button

![35](https://cloud.githubusercontent.com/assets/19830714/17765525/f0b77f1e-6558-11e6-9e34-098e3776f649.png)

**Comment by vernonminer** [comment]
Resolved by changing JavaScript file.

**Comment by jtolen** [comment]
Still encounter the same issue

![image](https://cloud.githubusercontent.com/assets/19830714/17794974/c6ef0c0e-65e6-11e6-8f78-3d491e67cd12.png)

**Comment by junpaolo** [comment]
see https://github.com/junpaolo/ePrice-validation-testing/issues/20
